contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #champlaintransferdata channel"
    url: https://nfcore.slack.com/channels/champlaintransferdata
    about: Discussion about the nf-core/champlaintransferdata pipeline
